### ISSUE TITLE
[Log]imprement parts to send Log to DB by using Go server.

### ISSUE THREAD

**Issue by Rwatana** [Rwatana/BlogService#6]
### Topic
Improve Logging System: Integrate Log Transmission to Go Server and Database

We are enhancing our logging system by implementing a new process to send logs from the application to a Go server and then to a database. This will provide a more robust and scalable logging solution.

## Tasks
- [ ] Develop the function to send logs to the Go server.
- [ ] Set up the Go server to handle incoming logs.
- [ ] Implement log forwarding from the Go server to the database.
- [ ] Integrate the logging function across various parts of the application.
- [ ] Conduct thorough testing to validate the entire logging flow.

## Schedule

6/23
